name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:
      - run: python --version
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: ls -la
      - run: python --version
      - run: uname -a
      - run: python -m pip install pytest, jsonschema
      - run: python -m pytest


